# Generated by Django 4.0.3 on 2022-10-22 21:47

import Material.models
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200, null=True)),
                ('materialDescription', models.TextField(max_length=3000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Desperfectos menores'), (3, 'Desperfectos moderados'), (4, 'Desperfectos graves')], default='Nuevo', max_length=50, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('factura', models.FileField(blank=True, null=True, upload_to=Material.models.uploadFileName)),
                ('alarma', models.BooleanField(default=False)),
                ('User', models.CharField(blank=True, max_length=60, null=True)),
                ('fotografia', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Material.models.uploadFileName)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRevision', models.DateTimeField(blank=True, null=True)),
                ('responsableRevision', models.CharField(blank=True, max_length=60, null=True)),
                ('estadoMastiles', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoCubeta', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoDobleTecho', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoEnganches', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoBolsas', models.CharField(blank=True, max_length=200, null=True)),
                ('numPiquetasUltraForte', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numPiquetasForte', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numPiquetasgEnerals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seGuardaSucia', models.BooleanField(default=False)),
                ('descripcionRevision', models.TextField(blank=True, null=True)),
                ('desperfectosReparadosLimpios', models.BooleanField(default=False)),
                ('fechaCierre', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Materiales/')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.revisionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material')),
            ],
        ),
    ]
