# Generated by Django 4.0.3 on 2022-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Desperfectos menores'), (3, 'Desperfectos moderados'), (4, 'Desperfectos graves')], default='Nuevo', null=True),
        ),
    ]
