# Generated by Django 4.0.3 on 2022-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0005_alter_material_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='User',
            field=models.CharField(blank=True, choices=[('colibri324', 'colibri324'), ('d4', 'd4'), ('d5', 'd5'), ('fernando', 'fernando'), ('milano324', 'milano324'), ('registerUser', 'registerUser')], max_length=50, null=True),
        ),
    ]
